layout_spectrum: 0.3566308
color:
  saturation: 0
  brandStrength: 0.9576776
  lightness: 1
  rhythmicContrast: 0.9587814
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
typography_spectrum: 0.6111111
name: ArtofDancefloor
